<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>USE_ZLIB;USE_LCMS2;LIBRAW_USE_OPENMP;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>C:\dev\{tmp}\PkgSrc\lcms2\lcms2\include;C:\dev\{tmp}\PkgSrc\zlib\64\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalDependencies>C:\dev\{tmp}\PkgSrc\lcms2\v143\lib\$(Platform)\$(Configuration)\lcms2_static.lib;C:\dev\{tmp}\PkgSrc\zlib\64\lib\z.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>